// portal/pages/normal/demo-badge.vue
<template>
    <div class="demo-badge">
        <im-demo-row title="基本用法">
            <im-badge :data="12">
                <im-button label="消息"/>
            </im-badge>
        </im-demo-row>
        <im-demo-row title="颜色">
            <im-badge :data="12" color="primary">
                <im-button label="消息"/>
            </im-badge>
            <im-badge :data="12" color="warn">
                <im-button label="消息"/>
            </im-badge>
            <im-badge :data="12" color="success">
                <im-button label="消息"/>
            </im-badge>
            <im-badge :data="12" color="error">
                <im-button label="消息"/>
            </im-badge>
            <im-badge :data="12" color="info">
                <im-button label="消息"/>
            </im-badge>
        </im-demo-row>
        <im-demo-row title="位置">
            <im-badge :data="12" :bottom="false" :start="true">
                <im-button label="消息"/>
            </im-badge>
            <im-badge :data="12" :bottom="false" :start="false">
                <im-button label="消息"/>
            </im-badge>
            <im-badge :data="12" :bottom="true" :start="true">
                <im-button label="消息"/>
            </im-badge>
            <im-badge :data="12" :bottom="true" :start="false">
                <im-button label="消息"/>
            </im-badge>
        </im-demo-row>
        <im-demo-row title="只要小红点">
            <im-badge dot>
                <im-button label="消息"/>
            </im-badge>
        </im-demo-row>
        <im-demo-row title="最大值">
            <im-badge :max="99" :data="200">
                <im-button label="消息"/>
            </im-badge>
        </im-demo-row>
    </div>
</template>

<script>
    export default {
        name: "demo-badge"
    }
</script>

<style lang="scss">
    .demo-badge {

    }
</style>

// story/pages/normal/DemoBadge.tsx
import {designPage} from "plain-ui-composition";
import {DemoRow} from "../../components/DemoRow";
import PlBadge from "../../../src/packages/PlBadge";
import PlButton from "../../../src/packages/PlButton";
import {StoryStatus} from "../../story.utils";

export default designPage(() => {
    return () => (
        <div>
            <DemoRow title={'基本用法'}>
                <PlBadge data={12}>
                    <PlButton label={'消息'}/>
                </PlBadge>
            </DemoRow>
            <DemoRow title={'颜色'}>
                {StoryStatus.map(item => (
                    <PlBadge data={12} key={item.status} status={item.status}>
                        <PlButton label={'消息'}/>
                    </PlBadge>
                ))}
            </DemoRow>
            <DemoRow title={'位置'}>
                <PlBadge data={12} bottom={false} start={true}>
                    <PlButton label={'消息'}/>
                </PlBadge>
                <PlBadge data={12} bottom={false} start={false}>
                    <PlButton label={'消息'}/>
                </PlBadge>
                <PlBadge data={12} bottom={true} start={true}>
                    <PlButton label={'消息'}/>
                </PlBadge>
                <PlBadge data={12} bottom={true} start={false}>
                    <PlButton label={'消息'}/>
                </PlBadge>
            </DemoRow>
            <DemoRow title={'仅显示小红点'}>
                <PlBadge data={12} dot>
                    <PlButton label={'消息'}/>
                </PlBadge>
            </DemoRow>
            <DemoRow title={'最大值'}>
                <PlBadge data={200} max={99}>
                    <PlButton label={'消息'}/>
                </PlBadge>
            </DemoRow>
        </div>
    )
})
