// src/packages/table/plc/plc-group.tsx
import {defineComponent} from "@vue/composition-api";
import {PlcGroupProps} from "@/packages/table/plc/plc-utils";
import {useSlots} from "@/use/useSlots";

export default defineComponent({
    name: 'plc-group',
    props: {
        ...PlcGroupProps,
    },
    setup(props) {

        const {slots} = useSlots()

        return () => (
            <div class="plc-group">
                {slots.default()}
            </div>
        )
    },
})

// src/packages/table/plc/core/plc-group.tsx
import {designComponent} from "../../../../use/designComponent";
import {PlcProps} from "./plc.utils";
import {TablePlcCollector} from './plc-collector';
import {useSlots} from "../../../../use/useSlots";

export default designComponent({
    name: 'plc-group',
    props: {
        ...PlcProps,
    },
    setup({props}) {

        const {slots} = useSlots()

        TablePlcCollector.useChild()
        TablePlcCollector.useParent()

        return {
            render: () => (
                <div>
                    {slots.default()}
                </div>
            )
        }
    },
})
