// src/packages/table/plc/core/plc.tsx
import {designComponent} from "../../../../use/designComponent";
import {PlcProps} from "./plc.utils";
import {TablePlcCollector} from './plc-collector';

export default designComponent({
    name: 'plc',
    props: {
        ...PlcProps,
    },
    setup({props}) {
        TablePlcCollector.useChild()
        return {
            render: () => (
                <div>
                    plc-{props.title}-{props.field}
                </div>
            )
        }
    },
})

// src/components/table/plc/plc.vue
<script>
    import {getPlcWatch, PlcMixin, PlcProps, PlcType} from "./plc-utils";

    export default {
        name: "plc",
        props: PlcProps,
        watch: {
            ...getPlcWatch(PlcProps)
        },
        mixins: [
            PlcMixin,
        ],
        data() {
            const plcType = PlcType.PLC

            return {
                plcType,
            }
        },
        render() {
            // return <span title={this.title} field={this.field}/>
            return null
        },
    }
</script>

<style lang="scss">

</style>
