// src/components/time/pl-time-panel.vue
<script>
    import {TimePublicProps} from "./subs";
    import {EmitMixin} from "../../utils/mixins";

    export default {
        name: "pl-time-panel",
        mixins: [
            EmitMixin,
        ],
        emitters: {
            emitInput: Function,
            emitUpdateStart: Function,
            emitUpdateEnd: Function,

            emitMousedownBasePanel: Function,
            emitMousedownStartPanel: Function,
            emitMousedownEndPanel: Function,
        },
        props: {
            value: {type: String},
            start: {type: String},
            end: {type: String},
            range: {type: Boolean},
            ...TimePublicProps,
        },
        watch: {
            value(val) {
                this.p_value = val
            },
            start(val) {
                this.p_start = val
            },
            end(val) {
                this.p_end = val
            },
        },
        data() {
            return {
                p_value: this.value,
                p_start: this.start,
                p_end: this.end,
            }
        },
        render(h) {
            const {base, range} = this.bindingProps
            return !this.range ? (
                <pl-time-base-panel class="pl-time-panel" {...base} key="base"/>
            ) : (
                <pl-time-range-panel class="pl-time-panel" {...range} key="range"/>
            )
        },
        computed: {
            bindingProps() {
                const publicProps = Object.keys(TimePublicProps).reduce((ret, key) => {
                    ret[key] = this[key]
                    return ret
                }, {})

                const base = {
                    props: {
                        ...publicProps,
                        value: this.p_value,
                    },
                    on: {
                        change: async (val) => {
                            await this.$plain.nextTick()

                            this.p_value = val
                            this.emitInput(this.p_value)
                        },
                        'mousedown-panel': this.emitMousedownBasePanel,
                    },
                }

                const range = {
                    props: {
                        ...publicProps,
                        start: this.p_start,
                        end: this.p_end,
                    },
                    on: {
                        change: async (val, type) => {
                            await this.$plain.nextTick()
                            if (type === 'start') {
                                this.p_start = val
                                this.emitUpdateStart(this.p_start)
                            } else if (type === 'end') {
                                this.p_end = val
                                this.emitUpdateEnd(this.p_end)
                            }
                            this.emitInput(val, type)
                        },
                        'mousedown-start-panel': this.emitMousedownStartPanel,
                        'mousedown-end-panel': this.emitMousedownEndPanel,
                    },
                }

                return {
                    base, range
                }
            },
        },
        methods: {},
    }
</script>

<style lang="scss">
</style>

// src/packages/PlTime/panel/PlTimePanel.tsx
import './time-range-panel.scss'
import {TimePublicProps} from "./time-panel.utils";
import {computed, designComponent, PropType, useModel} from "plain-ui-composition";
import {VueNode} from "react";
import PlTimeRangePanel, {TimeRangePanelType} from "./PlTimeRangePanel";
import {delay} from "plain-utils/utils/delay";

import PlTimeBasePanel from "./PlTimeBasePanel";

export const TimePanelProps = {
    modelValue: {type: String},
    start: {type: String},
    end: {type: String},
    range: {type: Boolean},
    ...TimePublicProps,
}

export const PlTimePanel = designComponent({
    name: 'pl-time-panel',
    props: {
        ...TimePanelProps,
        foot: {type: Function as PropType<() => VueNode>},
    },
    emits: {
        onUpdateModelValue: (val: string | undefined, type: TimeRangePanelType) => true,
        onUpdateStart: (val?: string) => true,
        onUpdateEnd: (val?: string) => true,

        onMousedownBasePanel: (e: MouseEvent) => true,
        onMousedownStartPanel: (e: MouseEvent) => true,
        onMousedownEndPanel: (e: MouseEvent) => true,
    },
    setup({props, event: {emit}}) {

        const model = useModel(() => props.modelValue, emit.onUpdateModelValue as any)
        const start = useModel(() => props.start, emit.onUpdateStart)
        const end = useModel(() => props.end, emit.onUpdateEnd)

        const handler = {
            onBaseChange: async (val?: string) => {
                await delay()
                model.value = val
            },
            onRangeChange: async (val: string | undefined, type: TimeRangePanelType) => {
                await delay()
                if (type === TimeRangePanelType.start) {
                    start.value = val
                } else if (type === TimeRangePanelType.end) {
                    end.value = val
                }
                emit.onUpdateModelValue(val, type)
            },
        }

        const binding = computed(() => {

            const publicProps = Object.keys(TimePublicProps).reduce((ret: any, key) => {
                ret[key] = (props as any)[key]
                return ret
            }, {})

            return {
                base: {
                    ...publicProps,
                    modelValue: model.value,
                    onChange: handler.onBaseChange,
                    onMousedown: emit.onMousedownBasePanel,
                },
                range: {
                    ...publicProps,
                    start: start.value,
                    end: end.value,
                    onChange: handler.onRangeChange,
                    onMousedownStartPanel: emit.onMousedownStartPanel,
                    onMousedownEndPanel: emit.onMousedownEndPanel,
                },
            }
        })

        return {
            render: () => <>
                {!props.range ?
                    <PlTimeBasePanel class="pl-time-panel" {...binding.value.base} key="base"/> :
                    <PlTimeRangePanel class="pl-time-panel" {...binding.value.range} key="range"/>}
                {!!props.foot && <div class="pl-time-panel-foot" onMousedown={emit.onMousedownBasePanel}>
                    {props.foot()}
                </div>}
            </>
        }

    },
})
