// story/pages/service/dialog-service.tsx
import {DemoRow} from "../../components/DemoRow";
import PlButton from "../../../src/packages/PlButton";
import useDialog from "../../../src/packages/useDialog";
import {StoryStatus} from "../../story.utils";
import $$message from "../../../src/packages/$$message";
import {designPage} from "plain-ui-composition";

export default designPage(() => {

    const $dialog = useDialog()

    const deleteConfirm = async () => {
        await $dialog.confirm('确认要删除该文件吗？')
        $$message.success('删除成功！')
    }

    const customDialog = () => {
        $dialog({
            title: '确认提示',
            dialogProps: {
                horizontal: 'end',
                transition: 'pl-transition-dialog-right',
                fullHeight: true,
                wrapperPadding: false,
            },
            render: () => {
                return (
                    <PlButton label={'hello world'}/>
                )
            },
        })
    }

    const multiService = (message = 1) => {
        const option = $dialog({
            render: () => {
                return (
                    <div>
                        <div>
                            {`第${message}个实例`}
                        </div>
                        <PlButton label="close" onClick={() => option.close()} style={{marginRight: '8px'}}/>
                        <PlButton label="open another dialog" onClick={() => multiService(message + 1)}/>
                    </div>
                )
            },
        })
    }

    let inputValue: string | undefined = '默认文本'

    return () => (
        <div>
            <DemoRow title={'基本用法'}>
                <PlButton label={'基本用法'} onClick={() => $dialog('操作成功')}/>
            </DemoRow>
            <DemoRow title={'提示状态'}>
                {StoryStatus.map(item => <PlButton
                    status={item.status} key={item.status} label={item.label}
                    onClick={() => $dialog[item.status]('操作进行中')}
                />)}
            </DemoRow>
            <DemoRow title={'确认对话框'}>
                <PlButton label={'删除'} onClick={deleteConfirm}/>
            </DemoRow>
            <DemoRow title={'去掉状态图标'}>
                <PlButton label={'去掉状态图标'} onClick={() => $dialog('hello world', {status: null})}/>
            </DemoRow>
            <DemoRow title={'dialog参数，以及自定义内容'}>
                <PlButton label={'自定义参数以及内容'} onClick={customDialog}/>
            </DemoRow>

            <DemoRow title={'输入对话框'}>
                <PlButton label={'input'} onClick={() => $dialog({
                    editType: 'input',
                    editValue: inputValue,
                    onConfirm: val => {
                        inputValue = val;
                        $$message(String(val))
                    },
                    confirmButton: true,
                    cancelButton: true,
                })}/>
                <PlButton label={'input readonly'} onClick={() => $dialog({
                    editType: 'input',
                    editValue: inputValue,
                    editReadonly: true,
                    onConfirm: val => {
                        inputValue = val;
                        $$message(String(val))
                    },
                    confirmButton: true,
                    cancelButton: true,
                })}/>
                <PlButton label={'textarea'} onClick={() => $dialog({
                    editType: 'textarea',
                    editValue: inputValue,
                    onConfirm: val => {
                        inputValue = val;
                        $$message(String(val))
                    },
                    confirmButton: true,
                    cancelButton: true,
                })}/>
                <PlButton label={'textarea'} onClick={() => $dialog({
                    editType: 'textarea',
                    editValue: inputValue,
                    editReadonly: true,
                    onConfirm: val => {
                        inputValue = val;
                        $$message(String(val))
                    },
                    confirmButton: true,
                    cancelButton: true,
                })}/>
                <PlButton label={'number'} onClick={() => $dialog({
                    editType: 'number',
                    editValue: 100,
                    onConfirm: val => {
                        $$message(String(val))
                    },
                    confirmButton: true,
                    cancelButton: true,
                })}/>
            </DemoRow>

            <DemoRow title={'多实例'}>
                <PlButton label={'open dialog'} onClick={() => multiService()}/>
            </DemoRow>
        </div>
    )
})

// src-doc/page/service/dialog-service.vue
<template>
    <div class="dialog-service">
        <demo-row title="基本用法">
            <pl-button label="基本用法" @click="$dialog('操作成功')"/>
        </demo-row>
        <demo-row title="提示状态">
            <pl-button :label="item" :status="item" @click="$dialog[item]('操作进行中')" v-for="item in status" :key="item"/>
        </demo-row>
        <demo-row title="去掉 状态 图标">
            <pl-button label="基本用法" @click="$dialog('操作成功',{status:null})"/>
        </demo-row>
        <demo-row title="dialog参数，以及自定义内容">
            <pl-button label="基本用法" @click="customOption"/>
        </demo-row>
        <demo-row title="输入对话框">
            <pl-button label="input" @click="$dialog({
                editType:'input',
                onConfirm:val=>$message(String(val)),
                confirmButton:true,
                cancelButton:true,
            })"/>
            <pl-button label="textarea" @click="$dialog({
                editType:'textarea',
                onConfirm:val=>$message(String(val)),
                confirmButton:true,
                cancelButton:true,
            })"/>
            <pl-button label="input readonly" @click="$dialog({
                editType:'input',
                editValue:'Hello world',
                editReadonly:true,
                onConfirm:val=>$message(String(val)),
                confirmButton:true,
                cancelButton:true,
            })"/>
            <pl-button label="textarea readonly" @click="$dialog({
                editType:'textarea',
                editValue:'Hello world',
                editReadonly:true,
                onConfirm:val=>$message(String(val)),
                confirmButton:true,
                cancelButton:true,
            })"/>
        </demo-row>

        <demo-row title="多实例">
            <pl-button label="基本用法" @click="multiService"/>
        </demo-row>
    </div>
</template>

<script>
    import DemoMixins from "../components/DemoMixins";

    export default {
        name: "dialog-service",
        props: {},
        mixins: [DemoMixins],
        data() {
            return {}
        },
        methods: {
            customOption() {

                let username, oldPwd, newPwd, repeatPwd;

                this.$dialog({
                    confirmButton: true,
                    cancelButton: true,
                    onConfirm: () => this.$message(JSON.stringify({username, oldPwd, newPwd, repeatPwd})),
                    onCancel: () => this.$message('cancel'),

                    title: '确认提示',
                    horizontal: 'end',
                    transition: 'pl-transition-dialog-right',
                    fullHeight: true,
                    wrapperPadding: false,

                    render() {
                        return (
                            <pl-form centerWhenSingleColumn rules={{}}>
                                <pl-form-item label="用户名">
                                    <pl-input onInput={val => username = val}/>
                                </pl-form-item>
                                <pl-form-item label="旧密码">
                                    <pl-input nativeProps={{type: "password"}} onInput={val => oldPwd = val}/>
                                </pl-form-item>
                                <pl-form-item label="新密码">
                                    <pl-input nativeProps={{type: "password"}} onInput={val => newPwd = val}/>
                                </pl-form-item>
                                <pl-form-item label="确认密码" required field="repeatPwd">
                                    <pl-input nativeProps={{type: "password"}} onInput={val => repeatPwd = val}/>
                                </pl-form-item>
                            </pl-form>
                        )
                    },
                })
            },
            multiService() {
                const that = this
                let message = Math.random()
                this.$dialog({
                    render() {
                        return (
                            <div>
                                message:{message}
                                <div>
                                    <pl-button label="open another dialog service" onClick={() => that.multiService()}/>
                                </div>
                            </div>
                        )
                    },
                })
            },
        },
    }
</script>

<style lang="scss">
</style>
